version: '3.4'

networks:
  network:
    driver: bridge

services:
  api:
    image: ${DOCKER_REGISTRY-}jobsityapi
    build:
      context: .
      dockerfile: JobSity.API/Dockerfile    
    ports:
      - "80"
    restart: on-failure
    networks:
      - network
    depends_on:
      - rabbit
      - db 
  rabbit:
    image: rabbitmq:3.9-management
    hostname: rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5
    networks:
      - network        
    expose:
     - 15672
     - 5672

  chatbot:
    build: 
        context: .
        dockerfile: JobSity.Bot/Dockerfile
    depends_on:
        - rabbit    
    restart: on-failure
    networks:
      - network        
    environment:
        - ASPNETCORE_ENVIRONMENT=Production

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "#Chat#Job"
      ACCEPT_EULA: "Y"
    networks:
      - network      
    ports:
      - "1433:1433"
  client:
    build:
      context: ../FRONT
      dockerfile: Dockerfile
    depends_on: 
      - api
    networks:
      - network      
    ports:
      - "4200:80"
  proxy:
    build: 
      context: ../nginx-proxy
      dockerfile: Dockerfile
    ports: 
      - "8200:80"
    networks:
      - network      
    restart: always
